version: '3.8'
services:
  n8n:
    build:
      context: .
      args:
        N8N_VERSION: 1.52.4
    image: ${N8N_IMAGE:-n8n-chromium:local}
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-changeme}
      - TZ=UTC
      - GENERIC_TIMEZONE=UTC
      - EXECUTIONS_MODE=regular
      - N8N_METRICS=true
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
volumes:
  n8n_data:
