name: Build and Push n8n Chromium Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: n8n-chromium
  # Pin a default version; can override via workflow inputs later
  N8N_VERSION: 1.52.4

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and Push (GHCR)
        run: |
          IMAGE_TAG_BASE=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          docker buildx build \
            --build-arg N8N_VERSION=${{ env.N8N_VERSION }} \
            -t $IMAGE_TAG_BASE:${{ env.N8N_VERSION }} \
            -t $IMAGE_TAG_BASE:latest \
            --push .

      - name: Build and Push (Docker Hub)
        if: env.DOCKERHUB_USERNAME && env.DOCKERHUB_TOKEN
        run: |
          IMAGE_TAG_BASE=${{ secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}
          docker buildx build \
            --build-arg N8N_VERSION=${{ env.N8N_VERSION }} \
            -t $IMAGE_TAG_BASE:${{ env.N8N_VERSION }} \
            -t $IMAGE_TAG_BASE:latest \
            --push .
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
